# Generated by Django 3.2 on 2021-05-11 19:17

import Zadanie_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zadanie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=Zadanie_app.models.file_directory_path),
        ),
        migrations.CreateModel(
            name='FileObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_values', models.IntegerField()),
                ('empty_values', models.IntegerField()),
                ('nan_values', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zadanie_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileNumerics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('std', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zadanie_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileHistogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='pictures/%Y/%m/%d/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zadanie_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zadanie_app.file')),
            ],
        ),
    ]
